Add empty separator check and tests
google/pygtrie pull request #18
Opened 2017-08-09 13:43 UTC by warenlg

I figured out you did not have any check for empty separators. I just added it with the corresponding tests.

2017-08-09 13:47 UTC, warenlg commented
I signed CLA

2017-08-09 13:56 UTC, vmarkovtsev requested changes

2017-08-09 13:56 UTC, vmarkovtsev commented on pygtrie.py
> +            raise Exception('separator can not be empty')
ValueError

2017-08-09 13:56 UTC, vmarkovtsev commented on pygtrie.py
> +        if sep is '':
`if not sep`

2017-08-09 13:56 UTC, vmarkovtsev commented on pygtrie.py
> +    def _separator(self, sep):
Add a type check for str and raise TypeError

2017-08-09 13:56 UTC, vmarkovtsev commented on test.py
> +        self.assertRaises(Exception, lambda: pygtrie.StringTrie(separator=''))
`with self.assertRaises`

2017-08-09 13:56 UTC, vmarkovtsev commented on pygtrie.py
> +        return self.__separator
I am fine with this, but the maintainers may not like this `__` Leaving as-is for now

2017-08-09 13:56 UTC, vmarkovtsev commented on test.py
> +        self.assertRaises(Exception, lambda: pygtrie.StringTrie(separator=''))
\+ do not forget to test TypeError

2017-08-09 15:04 UTC, mina86 requested changes

2017-08-09 15:04 UTC, mina86 commented on pygtrie.py
> +        return self.__separator
I don’t mind private fields. But I’m not sure why this needs to be done via a getter and setter. Why not just add a check in `__init__`?

2017-08-09 15:04 UTC, mina86 commented on pygtrie.py
> +    def _separator(self, sep):
This might be tricky with all the string mess and differences between Python 2 and 3 (recall that pygtrie supports both). I don’t mind either way.

2017-08-09 15:04 UTC, mina86 commented on test.py
> +    def testStringTrieSeparator(self):
test_string_trie_separator

Furthermore, this should be defined in StringTrieTestCase.

2017-08-09 15:04 UTC, mina86 commented on test.py
> +        self.assertRaises(Exception, lambda: pygtrie.StringTrie(separator=''))
Or `self.assertRaises(ValueError, pygtrie.StringTrie, separator='')`. I personally prefer this but don’t mind either.

2017-08-09 15:04 UTC, mina86 commented on test.py
> +        self.assertEqual(t._separator, ',')
I’d prefer the test not rely on accessing non-public properties, for example:

```
        t = pygtrie.StringTrie()
        t['foo/bar'] = 42
        self.assertTrue(bool(t.has_node('foo') & pygtrie.Trie.HAS_SUBTRIE))

        t = pygtrie.StringTrie(separator='.')
        t['foo.bar'] = 42
        self.assertTrue(bool(t.has_node('foo') & pygtrie.Trie.HAS_SUBTRIE))
```

2017-08-09 15:12 UTC, vmarkovtsev commented on pygtrie.py
> +    def _separator(self, sep):
If you don't mind importing `sys` here I would prefer to add the proper type check with string_types copied from https://github.com/JioCloud/python-six/blob/master/six.py#L41
We come from py3 world and have some troubles with mixed `bytes` and `str`

2017-08-09 15:14 UTC, vmarkovtsev commented on pygtrie.py
> +        return self.__separator
@warenlg - see, I offered you this simple check yesterday, no need to go smart unless the maintainers ask you.

2017-08-09 16:54 UTC, warenlg commented
Thanks reviewing, I committed again  based on your comments

2017-08-09 18:55 UTC, mina86 requested changes

2017-08-09 18:55 UTC, mina86 commented on pygtrie.py
> +        if not isinstance(separator, str):
This will break in Python 2 when unicode is used.

2017-08-09 18:55 UTC, mina86 commented on pygtrie.py
> +            raise TypeError('str is required')
`separator must be a string` would be a better message.

2017-08-09 18:55 UTC, mina86 commented on test.py
> +    def test_unvalid_separator(self):
invalid

2017-08-10 15:52 UTC, warenlg commented on pygtrie.py
> +        if not isinstance(separator, str):
thus, would you be ok doing it like this ?
```
separator = kwargs.pop('separator', '/')
        separator_type = type(separator).__name__
        if not separator_type in {'str', 'unicode'}:
            raise TypeError('separator must be a string')
```

2017-08-10 16:51 UTC, mina86 commented on pygtrie.py
> +        if not isinstance(separator, str):
If you want to check the type, one approach is to use the following at the beginning of the file:
```
try:
    _basestring = basestring
except NameError:
    _basestring = str
```
and then you can use `isinstance(…, _basestring)`. There already is some Python 2/3 compatibility code there.

Another option is to use solution pointed out by @vmarkovtsev: https://github.com/JioCloud/python-six/blob/master/six.py#L41. I don’t really like explicitly checking version thus I’m leaning towards code sample I’ve included above.

2017-08-14 12:39 UTC, warenlg commented on pygtrie.py
> +        if not isinstance(separator, str):
Tanks for your insights, I finally took the code sample you suggested to check the type

2017-08-14 13:09 UTC, mina86 commented
Pushed.

2017-08-14 13:09 UTC, closed without merging